name: Build & Publish docker

on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Latest Whisper GitHub Release
        id: get_release
        run: |
          release_url="https://api.github.com/repos/openai/whisper/releases/latest"
          latest_tag=$(curl https://api.github.com/repos/openai/whisper/releases/latest -s | jq -r .tag_name)
          echo "::set-output name=latest_tag::$latest_tag"
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "wortel538/openai-whisper:latest, wortel538/openai-whisper:${{ steps.get_release.outputs.latest_tag }}"
      - uses: actions/checkout@v2
      - name: Modify docker description
        uses: peter-evans/dockerhub-description@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: wortel538/openai-whisper
